title: "4 Parameter Example"

model:
  func_path: './examples/4_param_ode.py'
  parameters:
    kb1:
      init_guess: 1
      max: 1000000 
      min: 1.0e-10
    kb2:
      init_guess: 1
      max: 1000000 
      min: 1.0e-10 
    kh_plus:
      init_guess: 1
      max: 1000000
      min: 1.0e-10
    kh_minus:
      init_guess: 1
      max: 1000000
      min: 1.0e-10
  y0: [20.0e-9, 5000.0e-9, 5.0e-9, 0, 0, 0]
  max_value : 5.0e-9

fitter: 
  data_wells : ['C4:G4'] 
  control_wells: ['C2:G2']


integration:
  atol : 1.0e-8 
  rtol : 1.0e-6
  method: 'Radau' 

assay:
  file_path: './examples/data_2.xls'
  cols: 12
  rows : 8
  
  
  
  
